notify = ["/Users/alejo/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]
model = "gpt-5.5"
model_reasoning_effort = "xhigh"
service_tier = "fast"
approvals_reviewer = "user"

[projects."/Users/alejo"]
trust_level = "trusted"

[projects."/Users/alejo/Documents/aim"]
trust_level = "trusted"

[projects."/Users/alejo/Documents/dev"]
trust_level = "trusted"

[projects."/Users/alejo/Documents/Codex/2026-06-23/sites-plugin-sites-openai-bundled-create"]
trust_level = "trusted"

[projects."/Users/alejo/Documents/visa"]
trust_level = "trusted"

[projects."/Users/alejo/Documents/one-off"]
trust_level = "trusted"

[projects."/Users/alejo/Documents/people"]
trust_level = "trusted"

[projects."/Users/alejo/Documents/nonce"]
trust_level = "trusted"

[projects."/Users/alejo/Documents/best"]
trust_level = "trusted"

[projects."/Users/alejo/Documents/best/travel/visa"]
trust_level = "trusted"

[projects."/Users/alejo/best/travel/visa"]
trust_level = "trusted"

[projects."/Users/alejo/best"]
trust_level = "trusted"

[projects."/Users/alejo/nonce"]
trust_level = "trusted"

[projects."/Users/alejo/people"]
trust_level = "trusted"

[projects."/Users/alejo/thoughts"]
trust_level = "trusted"

[projects."/Users/alejo/Documents/Codex/2026-06-27/i-want-to-get-my-cloudflare"]
trust_level = "trusted"

[projects."/Users/alejo/Documents/Codex/2026-06-27/i-am-logging-on-google-chrome"]
trust_level = "trusted"

[projects."/Users/alejo/Documents/Codex/2026-06-27/can-you-search-documentation-of-computer"]
trust_level = "trusted"

[projects."/Users/alejo/Documents/Codex/2026-06-27/can-you-use-code-in-browser"]
trust_level = "trusted"

[projects."/Users/alejo/Documents/Codex/2026-06-28/can-you-use-code-in-browser"]
trust_level = "trusted"

[projects."/Users/alejo/projects"]
trust_level = "trusted"

[projects."/Users/alejo/best/make/art/meals/app"]
trust_level = "trusted"

[projects."/Users/alejo/Documents/Codex/2026-06-28/i-m-curious-can-you-use"]
trust_level = "trusted"

[projects."/Users/alejo/best/friends/places/visa"]
trust_level = "trusted"

[projects."/Users/alejo/Documents/Codex/2026-06-29/deploy-to-vercel-and-connect-to"]
trust_level = "trusted"

[projects."/Users/alejo/Documents/Codex/2026-06-29/deploy-to-vercel-and-connect-to-2"]
trust_level = "trusted"

[projects."/Users/alejo/Documents/Codex/2026-06-29/deploy-to-vercel-and-connect-to-3"]
trust_level = "trusted"

[projects."/Users/alejo/best/make/tools"]
trust_level = "trusted"

[projects."/Users/alejo/best/make/writing"]
trust_level = "trusted"

[tui.model_availability_nux]
"gpt-5.5" = 4

[history]
persistence = "save-all"

[marketplaces.openai-bundled]
last_updated = "2026-06-27T20:39:14Z"
source_type = "local"
source = "/Users/alejo/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-06-27T20:50:26Z"
source_type = "local"
source = "/Users/alejo/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins."browser@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[plugins."chrome@openai-bundled"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[features]
js_repl = false

[mcp_servers.node_repl]
args = []
command = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/Codex.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/alejo/.codex"
CODEX_HOME = "/Users/alejo/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "59e7bb81812ddd5f102e1d580335166e552c91686b5726218a985b59b4f89ca1"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.623.42026"
CODEX_CLI_PATH = "/Applications/Codex.app/Contents/Resources/codex"

[desktop]
conversationDetailMode = "STEPS_COMMANDS"
sansFontSize = 14
codeFontSize = 13
ambient-suggestions-enabled = true
followUpQueueMode = "queue"
localeOverride = "en-US"
mac-menu-bar-enabled = false
preventSleepWhileRunning = true
